export const mockData = [
  {
    id: 1,
    name: "Nissan",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    launchDate: 2005,
  },
  { id: 2, name: "Hyundai", description: "Accent", launchDate: 1998 },
  { id: 3, name: "Pontiac", description: "LeMans", launchDate: 1989 },
  { id: 4, name: "Chevrolet", description: "Cavalier", launchDate: 2002 },
  { id: 5, name: "Mitsubishi", description: "Endeavor", launchDate: 2007 },
  { id: 6, name: "Audi", description: "A7", launchDate: 2012 },
  { id: 7, name: "Mitsubishi", description: "Starion", launchDate: 1988 },
  { id: 8, name: "Ford", description: "LTD", launchDate: 1984 },
  { id: 9, name: "Ford", description: "Econoline E150", launchDate: 2001 },
  { id: 10, name: "Honda", description: "CR-V", launchDate: 2005 },
  { id: 11, name: "Mercury", description: "Capri", launchDate: 1993 },
  { id: 12, name: "Lincoln", description: "Mark VIII", launchDate: 1997 },
  { id: 13, name: "Ford", description: "F150", launchDate: 2003 },
  {
    id: 14,
    name: "Chevrolet",
    description: "Silverado 2500",
    launchDate: 2008,
  },
  { id: 15, name: "Toyota", description: "Supra", launchDate: 1996 },
  { id: 16, name: "Jaguar", description: "XK", launchDate: 2009 },
  { id: 17, name: "Pontiac", description: "Bonneville", launchDate: 1999 },
  { id: 18, name: "Cadillac", description: "Seville", launchDate: 2003 },
  { id: 19, name: "Dodge", description: "Intrepid", launchDate: 2002 },
  { id: 20, name: "Saab", description: "9-4X", launchDate: 2011 },
  { id: 21, name: "Chevrolet", description: "Metro", launchDate: 1998 },
  { id: 22, name: "Ford", description: "Bronco II", launchDate: 1984 },
  { id: 23, name: "Mitsubishi", description: "Raider", launchDate: 2006 },
  { id: 24, name: "Porsche", description: "924 S", launchDate: 1987 },
  { id: 25, name: "BMW", description: "X3", launchDate: 2010 },
  { id: 26, name: "Mitsubishi", description: "Truck", launchDate: 1996 },
  { id: 27, name: "Suzuki", description: "Vitara", launchDate: 2001 },
  { id: 28, name: "BMW", description: "M5", launchDate: 2002 },
  { id: 29, name: "Mercury", description: "Mariner", launchDate: 2006 },
  { id: 30, name: "Mercedes-Benz", description: "SLK-Class", launchDate: 2004 },
  { id: 31, name: "BMW", description: "5 Series", launchDate: 2004 },
  { id: 32, name: "MINI", description: "MINI", launchDate: 2002 },
  { id: 33, name: "GMC", description: "Savana 1500", launchDate: 2008 },
  { id: 34, name: "Chevrolet", description: "Malibu", launchDate: 2009 },
  { id: 35, name: "Chevrolet", description: "Suburban 2500", launchDate: 1995 },
  { id: 36, name: "Lexus", description: "LX", launchDate: 2008 },
  { id: 37, name: "Kia", description: "Sportage", launchDate: 2002 },
  { id: 38, name: "Saturn", description: "S-Series", launchDate: 1999 },
  { id: 39, name: "Acura", description: "TSX", launchDate: 2012 },
  { id: 40, name: "Mercedes-Benz", description: "300SD", launchDate: 1993 },
  { id: 41, name: "Volvo", description: "V50", launchDate: 2007 },
  { id: 42, name: "Chevrolet", description: "Monza", launchDate: 1975 },
  { id: 43, name: "Chevrolet", description: "Silverado", launchDate: 2002 },
  { id: 44, name: "Oldsmobile", description: "Silhouette", launchDate: 2004 },
  { id: 45, name: "Acura", description: "RDX", launchDate: 2008 },
  { id: 46, name: "Toyota", description: "Tacoma", launchDate: 2012 },
  { id: 47, name: "Toyota", description: "Prius v", launchDate: 2012 },
  { id: 48, name: "Ford", description: "E-Series", launchDate: 1991 },
  { id: 49, name: "Mazda", description: "Miata MX-5", launchDate: 1993 },
  { id: 50, name: "Subaru", description: "Impreza WRX", launchDate: 2010 },
  { id: 51, name: "Mitsubishi", description: "Challenger", launchDate: 2004 },
  { id: 52, name: "Lexus", description: "ES", launchDate: 2011 },
  { id: 53, name: "Suzuki", description: "Swift", launchDate: 1996 },
  { id: 54, name: "Ford", description: "Crown Victoria", launchDate: 1999 },
  { id: 55, name: "Toyota", description: "Tacoma", launchDate: 2006 },
  { id: 56, name: "Hyundai", description: "Accent", launchDate: 1995 },
  { id: 57, name: "Audi", description: "5000S", launchDate: 1984 },
  { id: 58, name: "Volvo", description: "XC90", launchDate: 2006 },
  { id: 59, name: "Cadillac", description: "Escalade EXT", launchDate: 2005 },
  { id: 60, name: "GMC", description: "Yukon XL 2500", launchDate: 2009 },
  { id: 61, name: "GMC", description: "1500 Club Coupe", launchDate: 1999 },
  { id: 62, name: "Hyundai", description: "Tiburon", launchDate: 1998 },
  { id: 63, name: "Toyota", description: "Land Cruiser", launchDate: 1995 },
  { id: 64, name: "Mazda", description: "Mazda5", launchDate: 2006 },
  { id: 65, name: "BMW", description: "6 Series", launchDate: 2004 },
  { id: 66, name: "Ford", description: "Thunderbird", launchDate: 1983 },
  { id: 67, name: "MINI", description: "Countryman", launchDate: 2011 },
  { id: 68, name: "Mazda", description: "MX-5", launchDate: 2002 },
  { id: 69, name: "Toyota", description: "Prius", launchDate: 2003 },
  { id: 70, name: "Pontiac", description: "Gemini", launchDate: 1986 },
  { id: 71, name: "Suzuki", description: "Sidekick", launchDate: 1995 },
  { id: 72, name: "GMC", description: "Acadia", launchDate: 2011 },
  { id: 73, name: "BMW", description: "325", launchDate: 2005 },
  { id: 74, name: "Mitsubishi", description: "Diamante", launchDate: 1999 },
  { id: 75, name: "Mercedes-Benz", description: "SL-Class", launchDate: 2002 },
  { id: 76, name: "Ford", description: "Bronco", launchDate: 1993 },
  { id: 77, name: "Porsche", description: "Cayenne", launchDate: 2004 },
  { id: 78, name: "Ford", description: "Windstar", launchDate: 2001 },
  { id: 79, name: "Lincoln", description: "Navigator L", launchDate: 2010 },
  { id: 80, name: "Lexus", description: "IS-F", launchDate: 2012 },
  { id: 81, name: "Chevrolet", description: "Camaro", launchDate: 2010 },
  { id: 82, name: "Lexus", description: "GS", launchDate: 1993 },
  { id: 83, name: "Lincoln", description: "Navigator", launchDate: 2007 },
  { id: 84, name: "Toyota", description: "Celica", launchDate: 1982 },
  { id: 85, name: "Lincoln", description: "Mark VII", launchDate: 1992 },
  { id: 86, name: "Lexus", description: "IS", launchDate: 2006 },
  { id: 87, name: "Oldsmobile", description: "Aurora", launchDate: 2002 },
  { id: 88, name: "Lexus", description: "ES", launchDate: 1998 },
  { id: 89, name: "Mazda", description: "MPV", launchDate: 1997 },
  { id: 90, name: "Ford", description: "Courier", launchDate: 1986 },
  { id: 91, name: "Ford", description: "Econoline E150", launchDate: 1995 },
  { id: 92, name: "GMC", description: "Envoy XUV", launchDate: 2004 },
  { id: 93, name: "Jaguar", description: "XJ", launchDate: 2010 },
  { id: 94, name: "Aston Martin", description: "Vantage", launchDate: 2009 },
  { id: 95, name: "Bentley", description: "Azure", launchDate: 2010 },
  { id: 96, name: "Acura", description: "TL", launchDate: 2012 },
  { id: 97, name: "GMC", description: "Sonoma Club Coupe", launchDate: 1994 },
  { id: 98, name: "Chevrolet", description: "Cobalt SS", launchDate: 2009 },
  { id: 99, name: "Mercedes-Benz", description: "C-Class", launchDate: 1993 },
  { id: 100, name: "Subaru", description: "Impreza", launchDate: 2005 },
];
